### ISSUE TITLE
ObjectId seems to be broken with MongoDB driver version 3

### ISSUE THREAD

**Issue by tmcdonnell87** [devbliss/mongojack#106]
Here's the error trying to call findOneById(id) with a string id:
Caused by: java.lang.IllegalAccessError: tried to access method org.bson.types.ObjectId.<init>(III)V from class org.mongojack.internal.stream.ObjectIdConver

The constructor for org.bson.types.ObjectId seems to have changed to no longer accept three parameters passed in org.mongojack.internal.stream.ObjectIdConvertor. 
http://api.mongodb.org/java/current/org/bson/types/ObjectId.html

Not sure if there is a good workaround.

**Comment by benmccann** [comment]
Can you past the full stack trace?

**Comment by tmcdonnell87** [comment]
Caused by: java.lang.IllegalAccessError: tried to access method org.bson.types.ObjectId.<init>(III)V from class org.mongojack.internal.stream.ObjectIdConvertor
	at org.mongojack.internal.stream.ObjectIdConvertor.convert(ObjectIdConvertor.java:30)
	at org.mongojack.internal.stream.DBDecoderBsonParser.getEmbeddedObject(DBDecoderBsonParser.java:70)
	at org.mongojack.internal.ObjectIdDeserializers$ToStringDeserializer.deserialize(ObjectIdDeserializers.java:41)
	at org.mongojack.internal.ObjectIdDeserializers$ToStringDeserializer.deserialize(ObjectIdDeserializers.java:37)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:106)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3023)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1676)
	at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:77)
	at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:64)
	at com.mongodb.DBDecoderAdapter.decode(DBDecoderAdapter.java:49)
	at com.mongodb.DBDecoderAdapter.decode(DBDecoderAdapter.java:29)
	at com.mongodb.connection.ReplyMessage.<init>(ReplyMessage.java:57)
	at com.mongodb.connection.QueryProtocol.receiveMessage(QueryProtocol.java:290)
	at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:229)
	at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:38)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:155)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:219)
	at com.mongodb.connection.DefaultServerConnection.query(DefaultServerConnection.java:166)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:397)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:394)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:195)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:168)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:394)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:57)
	at com.mongodb.Mongo.execute(Mongo.java:736)
	at com.mongodb.Mongo$2.execute(Mongo.java:723)
	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:815)
	at com.mongodb.DBCursor.hasNext(DBCursor.java:149)
	at org.mongojack.DBCursor.hasNext(DBCursor.java:348)
	at org.mongojack.JacksonDBCollection.findOne(JacksonDBCollection.java:1364)
	at org.mongojack.JacksonDBCollection.findOne(JacksonDBCollection.java:1334)
	at org.mongojack.JacksonDBCollection.findOneById(JacksonDBCollection.java:1282)
	at org.mongojack.JacksonDBCollection.findOneById(JacksonDBCollection.java:1269)
	at orders.OrderService.getOrderByID(OrderService.java:62)
        ... (rest of the stack)

**Comment by benmccann** [comment]
What version of mongojack are you using? Are you using the code in master on GitHub or a released version?

**Comment by tmcdonnell87** [comment]
3.0.1

**Comment by benmccann** [comment]
You can build the latest version from source and it should work. You can't update the driver until a new version of mongojack is released. I posted a note on the README to explain which versions are compatible with each other

**Comment by SinlyNi** [comment]
Excuse me！but i also meet the same qustion, it does't work, can u give me a hand thank u : 

version := "1.0"
scalaVersion := "2.11.7"
libraryDependencies ++= Seq(
  "org.scalanlp" %% "breeze" % "0.12",
  "com.databricks" %% "spark-csv" % "1.4.0",
  "org.apache.spark" %% "spark-sql" % "1.5.2"/* % "provided"*/,
  "org.apache.spark" %% "spark-core" % "1.5.2"/* % "provided"*/,
  "org.apache.spark" %% "spark-mllib" % "1.5.2",
  "org.mongodb.scala" %% "mongo-scala-driver" % "1.1.0",
  "org.apache.hadoop" %%"hadoop-client" % "2.2.0",
  "com.stratio.datasource" %%"spark-mongodb_2.10" % "0.11.2"
)
