### ISSUE TITLE
IN criteria over array fields

### ISSUE THREAD

**Issue by caeus** [devbliss/mongojack#107]
Let's assume I have a class `Parent` and a class `Child`.
Class `Parent` has a field `children` of type `List<ObjectId>`.
Now assume we want to find all the parents of a list of children.

    List<ObjectId> children = Arrays.asList(oi1,oi2,oi3,oi4...)
    parentsCollection.find(DBQuery.in("children",children)).toArray();

That throws an exception 
    Caused by: java.lang.ClassCastException: org.bson.types.ObjectId cannot be cast to java.util.Collection
        at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:24) ~[jackson-databind-2.5.3.jar:2.5.3]
        at org.mongojack.internal.util.SerializationUtils.serializeQueryField(SerializationUtils.java:265) ~[mongojack-2.3.0.jar:na]
        at org.mongojack.internal.util.SerializationUtils.serializeQueryCondition(SerializationUtils.java:183) ~[mongojack-2.3.0.jar:na]
        at org.mongojack.internal.util.SerializationUtils.serializeQueryCondition(SerializationUtils.java:194) ~[mongojack-2.3.0.jar:na]
        at org.mongojack.internal.util.SerializationUtils.serializeQuery(SerializationUtils.java:156) ~[mongojack-2.3.0.jar:na]
        at org.mongojack.internal.util.SerializationUtils.serializeQueryCondition(SerializationUtils.java:203) ~[mongojack-2.3.0.jar:na]
        at org.mongojack.internal.util.SerializationUtils.serializeQuery(SerializationUtils.java:156) ~[mongojack-2.3.0.jar:na]
        at org.mongojack.internal.util.SerializationUtils.serializeQuery(SerializationUtils.java:144) ~[mongojack-2.3.0.jar:na]
        at org.mongojack.JacksonDBCollection.serializeQuery(JacksonDBCollection.java:2318) ~[mongojack-2.3.0.jar:na]
        at org.mongojack.JacksonDBCollection.find(JacksonDBCollection.java:1180) ~[mongojack-2.3.0.jar:na]

Apparently the query serialization tries to be typesafe and so, the IN works only in non-array fields.
My workaround was to create my DBObject for the query manually. Thanks anyway, this lib is awesome!

**Comment by cberkeley** [comment]
I'm having a similar issue:
Something like this where users is an array of Strings : DBQuery.in("users", Arrays.asList("user1", "user2")); 
will throw this exception: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Collection

Any idea if I'm doing something wrong or if MongoJack is trying to cast a string to a collection? I'm using version 2.8.

**Comment by joschi** [comment]
Duplicate of #12
